package jee;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-23T15:43:07.138+01:00
 * Generated source version: 3.2.2
 *
 */
@WebServiceClient(name = "GestionVisiteService",
                  wsdlLocation = "file:/C:/Users/emili/git/GestionVisites/GestionVisites/WebContent/wsdl/gestionvisite.wsdl",
                  targetNamespace = "http://jee/")
public class GestionVisiteService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://jee/", "GestionVisiteService");
    public final static QName GestionVisitePort = new QName("http://jee/", "GestionVisitePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/emili/git/GestionVisites/GestionVisites/WebContent/wsdl/gestionvisite.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GestionVisiteService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/emili/git/GestionVisites/GestionVisites/WebContent/wsdl/gestionvisite.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GestionVisiteService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GestionVisiteService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GestionVisiteService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GestionVisiteService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GestionVisiteService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GestionVisiteService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GestionVisiteSEI
     */
    @WebEndpoint(name = "GestionVisitePort")
    public GestionVisiteSEI getGestionVisitePort() {
        return super.getPort(GestionVisitePort, GestionVisiteSEI.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GestionVisiteSEI
     */
    @WebEndpoint(name = "GestionVisitePort")
    public GestionVisiteSEI getGestionVisitePort(WebServiceFeature... features) {
        return super.getPort(GestionVisitePort, GestionVisiteSEI.class, features);
    }

}
