package jee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-23T15:43:07.127+01:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://jee/", name = "GestionVisiteSEI")
@XmlSeeAlso({ObjectFactory.class})
public interface GestionVisiteSEI {

    @WebMethod
    @RequestWrapper(localName = "annulerVisite", targetNamespace = "http://jee/", className = "jee.AnnulerVisite")
    @ResponseWrapper(localName = "annulerVisiteResponse", targetNamespace = "http://jee/", className = "jee.AnnulerVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean annulerVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "reserverVisite", targetNamespace = "http://jee/", className = "jee.ReserverVisite")
    @ResponseWrapper(localName = "reserverVisiteResponse", targetNamespace = "http://jee/", className = "jee.ReserverVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int reserverVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        jee.ReservationVisite arg0
    );

    @WebMethod
    @RequestWrapper(localName = "payerVisite", targetNamespace = "http://jee/", className = "jee.PayerVisite")
    @ResponseWrapper(localName = "payerVisiteResponse", targetNamespace = "http://jee/", className = "jee.PayerVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String payerVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );

    @WebMethod
    @RequestWrapper(localName = "trouverVisite", targetNamespace = "http://jee/", className = "jee.TrouverVisite")
    @ResponseWrapper(localName = "trouverVisiteResponse", targetNamespace = "http://jee/", className = "jee.TrouverVisiteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<jee.Visite> trouverVisite(
        @WebParam(name = "arg0", targetNamespace = "")
        jee.Visite arg0
    );
}
