
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package jee;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-23T15:43:07.107+01:00
 * Generated source version: 3.2.2
 *
 */

@javax.jws.WebService(
                      serviceName = "GestionVisiteService",
                      portName = "GestionVisitePort",
                      targetNamespace = "http://jee/",
                      wsdlLocation = "file:/C:/Users/emili/git/GestionVisites/GestionVisites/WebContent/wsdl/gestionvisite.wsdl",
                      endpointInterface = "jee.GestionVisiteSEI")

public class GestionVisitePortImpl implements GestionVisiteSEI {

    private static final Logger LOG = Logger.getLogger(GestionVisitePortImpl.class.getName());

    /* (non-Javadoc)
     * @see jee.GestionVisiteSEI#annulerVisite(int arg0)*
     */
    public boolean annulerVisite(int arg0) {
        LOG.info("Executing operation annulerVisite");
        System.out.println(arg0);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jee.GestionVisiteSEI#reserverVisite(jee.ReservationVisite arg0)*
     */
    public int reserverVisite(jee.ReservationVisite arg0) {
        LOG.info("Executing operation reserverVisite");
        System.out.println(arg0);
        try {
            int _return = 2086797067;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jee.GestionVisiteSEI#payerVisite(int arg0)*
     */
    public java.lang.String payerVisite(int arg0) {
        LOG.info("Executing operation payerVisite");
        System.out.println(arg0);
        try {
            java.lang.String _return = "_return-1944381341";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see jee.GestionVisiteSEI#trouverVisite(jee.Visite arg0)*
     */
    public java.util.List<jee.Visite> trouverVisite(jee.Visite arg0) {
        LOG.info("Executing operation trouverVisite");
        System.out.println(arg0);
        try {
            java.util.List<jee.Visite> _return = new java.util.ArrayList<jee.Visite>();
            jee.Visite _returnVal1 = new jee.Visite();
            _returnVal1.setDateVisite("DateVisite722439291");
            _returnVal1.setIdVisite(-1710622494);
            _returnVal1.setPrixVisite(155252038);
            _returnVal1.setTypeVisite("TypeVisite-767421547");
            _returnVal1.setVille("Ville-2048340574");
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
