
package jee;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-23T15:43:07.055+01:00
 * Generated source version: 3.2.2
 *
 */
public final class GestionVisiteSEI_GestionVisitePort_Client {

    private static final QName SERVICE_NAME = new QName("http://jee/", "GestionVisiteService");

    private GestionVisiteSEI_GestionVisitePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = GestionVisiteService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        GestionVisiteService ss = new GestionVisiteService(wsdlURL, SERVICE_NAME);
        GestionVisiteSEI port = ss.getGestionVisitePort();

        {
        System.out.println("Invoking annulerVisite...");
        int _annulerVisite_arg0 = 803014513;
        boolean _annulerVisite__return = port.annulerVisite(_annulerVisite_arg0);
        System.out.println("annulerVisite.result=" + _annulerVisite__return);


        }
        {
        System.out.println("Invoking reserverVisite...");
        jee.ReservationVisite _reserverVisite_arg0 = new jee.ReservationVisite();
        _reserverVisite_arg0.setIdClient(-888587189);
        _reserverVisite_arg0.setIdReservation(624223940);
        _reserverVisite_arg0.setIdVisite(-1493197897);
        _reserverVisite_arg0.setNombrePlace(-857119017);
        _reserverVisite_arg0.setPaiementEffectue(false);
        int _reserverVisite__return = port.reserverVisite(_reserverVisite_arg0);
        System.out.println("reserverVisite.result=" + _reserverVisite__return);


        }
        {
        System.out.println("Invoking payerVisite...");
        int _payerVisite_arg0 = 55168836;
        java.lang.String _payerVisite__return = port.payerVisite(_payerVisite_arg0);
        System.out.println("payerVisite.result=" + _payerVisite__return);


        }
        {
        System.out.println("Invoking trouverVisite...");
        jee.Visite _trouverVisite_arg0 = new jee.Visite();
        _trouverVisite_arg0.setDateVisite("DateVisite1232771179");
        _trouverVisite_arg0.setIdVisite(-404591083);
        _trouverVisite_arg0.setPrixVisite(-1206262836);
        _trouverVisite_arg0.setTypeVisite("TypeVisite272700113");
        _trouverVisite_arg0.setVille("Ville2125737337");
        java.util.List<jee.Visite> _trouverVisite__return = port.trouverVisite(_trouverVisite_arg0);
        System.out.println("trouverVisite.result=" + _trouverVisite__return);


        }

        System.exit(0);
    }

}
